[package]
name = "findr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
clap = "4.5.20"
regex = "1.11.1"
thiserror = "1.0.67"
walkdir = "2.5.0"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
pretty_assertions = "1.4.1"
rand = "0.8.5"
